apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabric-data-agent-sa
  namespace: fabric-data-agent
  annotations:
    # mskr-aks-cluster-uami clientID
    azure.workload.identity/client-id: "1cdb01c5-ab92-457a-b1a7-ce84cf1c8789"
  labels:
    azure.workload.identity/use: "true"
